#!/usr/bin/env python3

import argparse, sys, csv
parser = argparse.ArgumentParser(description="Integrate prefix.tab with additional names (replacing those prefix.tab)",
                                 add_help=True)
parser.add_argument('-p','--prefix',required=False,type=argparse.FileType('r'),default="prefix.tab",
                    help="prefix.tab file is the default, generated by Phyling init  - tab delimited 2 cols: Prefix<tab>LongName")
parser.add_argument('-i','--intable',required=True,type=argparse.FileType('r'),
                    help="File with additional prefixes to override what was parsed from input pep folder names")

args = parser.parse_args(sys.argv[1:])

starting = csv.reader(args.prefix,delimiter="\t")
prefixes = {}
for row in starting:
    pref = row[0]
    name = row[1]
    if pref in prefixes:
        print("found %s in row %s, but already stored for %s, prefix input file is not unique?"%(pref,name,prefixes[pref]))

    prefixes[pref] = name

adding = csv.reader(args.intable,delimiter="\t")
for row in adding:
    pref = row[0]
    name = row[1]
    if pref in prefixes:
        prefixes[pref] = name

for prefix in sorted(prefixes.keys(), key=lambda x: prefixes[x]):
    print("\t".join([prefix,prefixes[prefix]]))
