
HMM        ?=fungi_odb10
OUTPEPEXT  ?= aa.fa
OUTCDSEXT  ?= cds.fa
HMMALIGN   ?= hmmalign
REFORMAT   ?= esl-reformat
TRIMAL     ?= trimal
CLIPKIT	   ?= clipkit
RESOVERLAP ?= 0.70
SEQOVERLAP ?= 80
TRIMALSCHEME ?=-automated1
MRTRANS    ?= bp_mrtrans.pl
HMMFOLDER  ?= $(realpath HMM/${HMM}/HMM3)
ALNDIR     ?= $(realpath aln/${HMM})

#$(info "${HMMFOLDER} is HMMFOLDER")
#CWD := $(shell pwd)

seqs    = $(wildcard ${ALNDIR}/*.$(OUTPEPEXT))
cdsseqs = $(wildcard ${ALNDIR}/*.$(OUTCDSEXT))
msa     = $(seqs:.fa=.msa)
clean   = $(seqs:.fa=.clnaln)
filter  = $(seqs:.fa=.filter)
trim    = $(seqs:.fa=.trim)
clipkit = $(seqs:.fa=.clipkit)
cdsaln = $(cdsseqs:.fa=.cds.msa)

all: $(clipkit) $(cdsaln)

.PHONY: clean all

clean:
	rm -f *.msa *.clnaln *.filter *.trim *.clipkit

empty    :=
trailAA  := .aa.fa
trailCDS := .cds.fa
trailAAALN := .aa.msa
trailAACLN := .aa.mfa

%.aa.msa : %.aa.fa
	$(eval marker=$(subst $(trailAA),$(empty),$(notdir $<)))
	${HMMALIGN} --trim --amino -o $@ ${HMMFOLDER}/${marker}.hmm $<

%.cds.msa : %.cds.fa
	$(eval marker=$(subst $(trailCDS),$(empty),$(notdir $<)))
	$(eval AAFILE=$(subst $(trailCDS),$(trailAA),$<))
	$(eval ALN=$(subst $(trailAA),$(trailAAALN),${AAFILE}))
	$(eval ALNCLN=$(subst $(trailAA),$(trailAACLN),${AAFILE}))

	${HMMALIGN} --trim --amino -o ${ALN} ${HMMFOLDER}/${marker}.hmm ${AAFILE}
	esl-reformat --replace=x:- --gapsym=- afa ${ALN} | perl -p -e 'if (! /^>/) { s/[ZBzbXx\*]/-/g }' > ${ALNCLN}

	${MRTRANS} -if fasta -of fasta -i ${ALNCLN} -s $< -o $@

%.clnaln : %.msa
	esl-reformat --replace=x:- --gapsym=- afa $< | perl -p -e 'if (! /^>/) { s/[ZBzbXx\*]/-/g }' > $@

%.filter : %.clnaln
	trimal -resoverlap ${RESOVERLAP} -seqoverlap ${SEQOVERLAP} -in $< -out $@

%.trim : %.filter
	trimal ${TRIMALSCHEME} -fasta -in $< -out $@

%.clipkit : %.clnaln
	clipkit -o $@ $<
