
HMM        ?=fungi_odb10
OUTEXT     ?= clipkit
ALNDIR     ?= $(realpath aln/${HMM})
IQTREE     ?= iqtree2
IQCPU      ?= 1
FASTTREE   ?= FastTreeMP

trailCDS  := .cds.clipkit
trailAA   := .aa.clipkit

#$(info "${HMMFOLDER} is HMMFOLDER")

CDSiqtrees  := $(patsubst %.clipkit,%.clipkit.treefile,$(wildcard ${ALNDIR}/*.cds.clipkit))
AAiqtrees   := $(patsubst %.clipkit,%.clipkit.treefile,$(wildcard ${ALNDIR}/*.aa.clipkit))
CDSFTtrees  := $(patsubst %.clipkit,%.clipkit.FT.tre,$(wildcard ${ALNDIR}/*.cds.clipkit))
AAFTtrees   := $(patsubst %.clipkit,%.clipkit.FT.tre,$(wildcard ${ALNDIR}/*.aa.clipkit))

#$(info $(CDSFTtrees))
#$(info $(AAFTtrees))
#$(info $(AAiqtrees))
#$(info $(CDSiqtrees))
# $(iqtrees)
all: $(AAFTtrees) $(CDSFTtrees)
CDS: $(CDSFTtrees)
PEP: $(AAFTtrees)

CDSIQ: $(CDSiqtrees)
PEPIQ: $(AAiqtrees)

.PHONY: clean all

clean:
	rm -f *.FT.tre *.treefile

empty    :=

%.clipkit.spname : %.clipkit
	perl -p -e 's/\|/ /' $< > $@

%.treefile : %.spname
#	$(info "args are" $@ " and " $< " and " $@.treefile)
	${IQTREE} -s $< -nt ${IQCPU} -B 1000 -alrt 1000

%.aa.clipkit.FT.tre : %.aa.clipkit.spname
#		$(info "args are" $@ " and " $<)
		${FASTTREE} -lg $< > $@

%.cds.clipkit.FT.tre : %.cds.clipkit.spname
#		$(info "args are" $@ " and " $<)
		${FASTTREE} -gtr -nt $< > $@
