# this assumes something about the PHYling setup

MDIR       := $(shell dirname $(realpath $(MAKEFILE_LIST)))
UTILDIR    := $(shell dirname ${MDIR})
HMM        ?= fungi_odb10
OUTPEPEXT  ?= aa.fa
OUTCDSEXT  ?= cds.fa
HMMALIGN   ?= hmmalign
REFORMAT   ?= esl-reformat
TRIMAL     ?= trimal
CLIPKIT	   ?= clipkit
RESOVERLAP ?= 0.70
SEQOVERLAP ?= 80
TRIMALSCHEME ?=-automated1
MRTRANS     ?= ${UTILDIR}/bp_mrtrans_filt.pl
#HMMFOLDER  ?= $(realpath HMM/$(HMM)/HMM3)
#ALNDIR     ?= $(realpath aln/$(HMM))

HMMFOLDER  ?= HMM/$(HMM)/HMM3
ALNDIR     ?= aln/$(HMM)

seqs    = $(wildcard ${ALNDIR}/*.$(OUTPEPEXT))
cdsseqs = $(wildcard ${ALNDIR}/*.$(OUTCDSEXT))
msa     = $(seqs:.fa=.msa)

#clean   = $(seqs:.fa=.clnaln)
#filter  = $(seqs:.fa=.filter)
#trim    = $(seqs:.fa=.trim)
aaaln    = $(seqs:.fa=.clipkit)
cdsaln   = $(cdsseqs:.fa=.clipkit)

#$(info "$(cdsaln) is cdsaln")
#$(info "$(aaaln) is aaaln")

all: $(clipkit) $(cdsaln)

.PHONY: clean all

clean:
	rm -f *.msa *.clnaln *.filter *.trim *.clipkit

empty    :=
trailAA  := .aa.fa
trailCDS := .cds.fa
AAALN    := .aa.msa
AACLN    := .aa.mfa

%.aa.clipkit : %.aa.fa
	$(eval marker=$(subst $(trailAA),$(empty),$(notdir $<)))
	${HMMALIGN} --amino -o ${ALNDIR}/${marker}.aa.msa ${HMMFOLDER}/${marker}.hmm $<
	esl-reformat --replace=x:- --gapsym=- afa ${ALNDIR}/${marker}.aa.msa | perl -p -e 'if (! /^>/) { s/[ZBzbXx\*]/-/g }' > ${ALNDIR}/${marker}.aa.clnaln
	clipkit --log -m gappy -o $@ ${ALNDIR}/${marker}.aa.clnaln

%.cds.clipkit : %.cds.fa
	$(eval marker=$(subst $(trailCDS),$(empty),$(notdir $<)))
	${MRTRANS} -if fasta -of fasta -i ${ALNDIR}/${marker}.aa.clnaln -s $< -o $@ --filter ${ALNDIR}/${marker}.aa.clipkit.log
