name: Build raxml-ng

on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string
        default: "2.0.2"

jobs:
  build_raxml:
    name: Build raxml-ng
    runs-on: ubuntu-latest

    env:
      URL: ${{ format('https://github.com/amkozlov/raxml-ng/releases/download/{0}/raxml-ng_v{0}_linux_x86_64.zip', inputs.version) }}

    steps:
      - name: Check for cached binary
        id: binary-cache
        uses: actions/cache@v6
        with:
          path: bin-payload/raxml-ng
          key: ${{ runner.os }}-raxml

      - name: Install dependencies
        if: steps.binary-cache.outputs.cache-hit != 'true'
        run: |
          sudo apt update
          sudo apt-get install build-essential g++ wget unzip

      - name: Compile/Download
        if: steps.binary-cache.outputs.cache-hit != 'true'
        run: |
          wget ${{ env.URL }}
          unzip raxml-ng_v${{ inputs.version }}_linux_x86_64.zip

      - name: Move executable
        if: steps.binary-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p bin-payload
          cp raxml-ng bin-payload/
          chmod +x bin-payload/raxml-ng

      - name: Verify executable locally
        run: ./bin-payload/raxml-ng --help || true

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: raxml-binary-payload
          path: bin-payload/raxml-ng
