name: Build FastTree

on: workflow_call

jobs:
  build_fasttree:
    name: Build FastTree
    runs-on: ubuntu-latest

    env:
      URL: http://www.microbesonline.org/fasttree/FastTree

    steps:
      - name: Check for cached binary
        id: binary-cache
        uses: actions/cache@v6
        with:
          path: bin-payload/FastTree
          key: ${{ runner.os }}-fasttree

      - name: Install dependencies
        if: steps.binary-cache.outputs.cache-hit != 'true'
        run: |
          sudo apt update
          sudo apt-get install wget

      - name: Compile/Download
        if: steps.binary-cache.outputs.cache-hit != 'true'
        run: wget ${{ env.URL }}

      - name: Move executable
        if: steps.binary-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p bin-payload
          cp FastTree bin-payload/
          chmod +x bin-payload/FastTree

      - name: Verify executable locally
        run: ./bin-payload/FastTree --help || true

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: fasttree-binary-payload
          path: bin-payload/FastTree
