name: Build IQTree

on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string
        default: "3.1.2"

jobs:
  build_iqtree:
    name: Build IQTree
    runs-on: ubuntu-latest

    env:
      URL: ${{ format('https://github.com/iqtree/iqtree3/releases/download/v{0}/iqtree-{0}-Linux-intel.tar.gz', inputs.version) }}

    steps:
      - name: Check for cached binary
        id: binary-cache
        uses: actions/cache@v6
        with:
          path: bin-payload/iqtree3
          key: ${{ runner.os }}-iqtree

      - name: Install dependencies
        if: steps.binary-cache.outputs.cache-hit != 'true'
        run: |
          sudo apt update
          sudo apt-get install wget

      - name: Compile/Download
        if: steps.binary-cache.outputs.cache-hit != 'true'
        run: |
          wget ${{ env.URL }}
          tar zxf iqtree-${{ inputs.version }}-Linux-intel.tar.gz

      - name: Move executable
        if: steps.binary-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p bin-payload
          cp iqtree-${{ inputs.version }}-Linux-intel/bin/iqtree3 bin-payload/
          chmod +x bin-payload/iqtree3

      - name: Verify executable locally
        run: ./bin-payload/iqtree3 --help || true

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: iqtree-binary-payload
          path: bin-payload/iqtree3
