name: Build ASTER

on:
  workflow_call:

jobs:
  build_aster:
    name: Build ASTER
    runs-on: ubuntu-latest
    env:
      URL: https://github.com/chaoszhang/ASTER/archive/refs/heads/Linux.zip

    steps:
      - name: Check for cached binary
        id: binary-cache
        uses: actions/cache@v6
        with:
          path: bin-payload/astral
          key: ${{ runner.os }}-aster

      - name: Install dependencies
        if: steps.binary-cache.outputs.cache-hit != 'true'
        run: |
          sudo apt update
          sudo apt-get install build-essential cmake g++ wget unzip

      - name: Compile/Download
        if: steps.binary-cache.outputs.cache-hit != 'true'
        run: |
          wget ${{ env.URL }}
          unzip Linux.zip
          cd ASTER-Linux
          make

      - name: Move executable
        if: steps.binary-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p bin-payload
          cp ASTER-Linux/bin/astral bin-payload/
          chmod +x bin-payload/astral

      - name: Verify executable locally
        run: ./bin-payload/astral --help || true

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: aster-binary-payload
          path: bin-payload/astral
