name: Build muscle

on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string
        default: "5.3"

jobs:
  build_muscle:
    name: Build muscle
    runs-on: ubuntu-latest

    env:
      URL: ${{ format('https://github.com/rcedgar/muscle/releases/download/v{0}/muscle-linux-x86.v{0}', inputs.version) }}

    steps:
      - name: Check for cached binary
        id: binary-cache
        uses: actions/cache@v6
        with:
          path: bin-payload/muscle
          key: ${{ runner.os }}-muscle

      - name: Install dependencies
        if: steps.binary-cache.outputs.cache-hit != 'true'
        run: |
          sudo apt update
          sudo apt-get install wget

      - name: Compile/Download
        if: steps.binary-cache.outputs.cache-hit != 'true'
        run: |
          wget ${{ env.URL }}
          mv muscle-linux-x86.v${{ inputs.version }} muscle

      - name: Move executable
        if: steps.binary-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p bin-payload
          cp muscle bin-payload/
          chmod +x bin-payload/muscle

      - name: Verify executable locally
        run: ./bin-payload/muscle --help || true

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: muscle-binary-payload
          path: bin-payload/muscle
